"""added some models

Revision ID: 23d781cba4c3
Revises: 
Create Date: 2024-04-01 15:51:39.237686

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '23d781cba4c3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classrooms',
    sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False)
    )

    op.create_table('teachers',
    sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False, unique=True),
    sa.Column('specialty', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False)
    )

    op.create_table('preceptors',
    sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False, unique=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False)
    )

    op.create_table('students',
    sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('document', sa.String(), nullable=False, unique=True),
    sa.Column('email', sa.String(), nullable=False, unique=True),
    sa.Column('nationality', sa.String(), nullable=False),
    sa.Column('classroom_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('classrooms.id'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False)
    )

    op.create_table('courses',
    sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('teacher_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('teachers.id'), nullable=False),
    sa.Column('preceptor_id', postgresql.UUID(as_uuid=True), sa.ForeignKey('preceptors.id'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False)
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('courses')
    op.drop_table('students')
    op.drop_table('preceptors')
    op.drop_table('teachers')
    op.drop_table('classrooms')
    # ### end Alembic commands ###
