"""added user model

Revision ID: 33818da4d544
Revises: 23d781cba4c3
Create Date: 2024-04-01 15:57:49.553847

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '33818da4d544'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
                    sa.Column('id', postgresql.UUID(as_uuid=True), primary_key=True),
                    sa.Column('name', sa.String(length=128), nullable=False),
                    sa.Column('last_name', sa.String(length=128), nullable=False),
                    sa.Column('email', sa.String(length=128), nullable=False, unique=True),
                    sa.Column('username', sa.String(length=128), nullable=False, unique=True),
                    sa.Column('password', sa.String(length=255), nullable=False),
                    sa.Column('is_active', sa.Boolean(), nullable=False),
                    sa.Column('is_admin', sa.Boolean(), nullable=False),
                    sa.Column('created_at', sa.DateTime(), nullable=False),
                    sa.Column('updated_at', sa.DateTime(), nullable=False),
                    sa.Column('is_deleted', sa.Boolean(), nullable=False)
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
