version: '3.3'

networks:
  school-network:
    name: school-network
    external: true


services:
  school-db:
    image: postgres:11.4
    ports:
      - "5432:5432"
    networks:
      - school-network
    environment:
      POSTGRES_DB: test_dbschool


  school-api:
    build: .
    volumes:
      - ./:/app
    env_file:
      - .env
    ports:
      - "8000:8000"
    networks:
      - school-network
    depends_on:
      - school-db
